# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: continuumio/miniconda3:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.

variables:
    TWINE_USERNAME: xumi1993
    TWINE_PASSWORD: Nanwai99

before_script:
  - conda config --set always_yes yes
  - conda config --add channels https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - conda config --add channels https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - conda config --add channels conda-forge
  # - conda config --add channels https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
  - conda info -a

# test:
#   script:
#     - python setup.py test
#     - pip install tox flake8  # you can also use tox
#     - tox -e py36,flake8

py37:
  script:
    - conda create -n testenv37 python=3.7
    - source activate testenv37
    - pip install twine setuptools wheel
    - python setup.py sdist bdist_wheel
    # an alternative approach is to install and run:
    # run the command here

py36:
  script:
    - conda create -n testenv36 python=3.6
    - source activate testenv36
    - pip install twine setuptools wheel
    - python setup.py sdist bdist_wheel
    
after_script:
    - twine upload dist/*
    
