image: continuumio/miniconda3:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.

before_script:
  - conda config --set always_yes yes
  - conda update -q conda
  - conda config --add channels https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - conda config --add channels https://mirrors.ustc.edu.cn/anaconda/pkgs/main/